### PR TITLE
Major Changes

### PR DESCRIPTION
**Pull request by jakevolkman**
I've edited the ship classes and added a new one. The ship class now has a type variable, which is the only difference between each class at the moment. This is changed in the constructor.
Additionally, everything works on 4 arraylists now, instead of 8.. The lists contain type data that can be read by javascript. I accomplished this by adding a new class ShotData that contains the coordinates and the ship type.
Now all that really needs work is the front end, and sinking civilian ships in one shot.
Cheers.

### CODE REVIEW

**Comment by dmkato** [comment]
Wow dude this looks really good! Thanks for figuring out how to make the child classes.

**Comment by dmkato** [comment]
I'm gonna go ahead and check this out on my machine before I merge it

**Comment by jakevolkman** [comment]
OK let me know if it works

**Comment by dmkato** [comment]
Ok, so like the game doesn't work when I try to play it. Like I can click coordinates, but a Rick/Morty head doesn't pop up, and the computer doesn't shoot after.

**Comment by jakevolkman** [comment]
That makes sense. You need to access the arraylists in the javascripts with an addtional objects. For some reason my js still works but I figured it was an issue with IntelliJ compiling an old version beause when I tried to make a change in the js it stopped working.
Theoretically it should work if you change every object call like "gameModel.playerMisses[i].Across" to "gameModel.playerMisses[i].loc.Across". The object has an additional object to go through now.

**Comment by jakevolkman** [comment]
Also it does still run on mine. I committed everything and pushed and it still runs. So this is something in IntelliJ that isn't updating my app.js file when rebuilding the project.

**Comment by jakevolkman** [comment]
alright that should fix it

**Comment by jakevolkman** [comment]
Yup it works now

**Comment by dmkato** [comment]
Good work dude! I checked out the latest commit and everything works! Also the UI updates look very nice and clean.

**Pull request merged**
